INSERT INTO ALUNOS (MATRICULA, NOME_COMPLETO)VALUES(2019011235, 'ADRIANO PEREIRA DA COSTA');
INSERT INTO ALUNOS (MATRICULA, NOME_COMPLETO)VALUES(2018010134, 'ALICE IELLY SANTOS MARROCOS');
INSERT INTO ALUNOS (MATRICULA, NOME_COMPLETO)VALUES(2016020915, 'ADRIANO PEREIRA DA COSTA');
INSERT INTO ALUNOS (MATRICULA, NOME_COMPLETO)VALUES(2016020915, 'ANNA LUIZA DE ARAUJO FRUTUOSO');
INSERT INTO ALUNOS (MATRICULA, NOME_COMPLETO)VALUES(2019022827, 'ANNYSHERLE KARLA DE MACEDO VIANA CAVALCANTE');
INSERT INTO ALUNOS (MATRICULA, NOME_COMPLETO)VALUES(2016021169, 'EDIGELZA DE ABREU');
INSERT INTO ALUNOS (MATRICULA, NOME_COMPLETO)VALUES(2018010455, 'ERALDO PALHARES FERREIRA');
INSERT INTO ALUNOS (MATRICULA, NOME_COMPLETO)VALUES(2018022221, 'FABIO LUIZ MARIANO DA SILVA');
INSERT INTO ALUNOS (MATRICULA, NOME_COMPLETO)VALUES(2019010582, 'FRANCISCO JAEDSON CAMARA');
INSERT INTO ALUNOS (MATRICULA, NOME_COMPLETO)VALUES(2019010625, 'GABRIEL BARBOSA DOS SANTOS');

INSERT INTO REFEICOES (TIPO_REFEICAO, DATA_REFEICAO, CAMPI, ID_ALUNO)VALUES('ALMOCO', '2020-11-29', 'PAU_DOS_FERROS', 2);
INSERT INTO REFEICOES (TIPO_REFEICAO, DATA_REFEICAO, CAMPI, ID_ALUNO)VALUES('JANTAR', '2020-11-29', 'ANGICOS', 3);
INSERT INTO REFEICOES (TIPO_REFEICAO, DATA_REFEICAO, CAMPI, ID_ALUNO)VALUES('ALMOCO', '2020-11-29', 'MOSSORO', 8);
INSERT INTO REFEICOES (TIPO_REFEICAO, DATA_REFEICAO, CAMPI, ID_ALUNO)VALUES('JANTAR', '2020-11-29', 'ANGICOS', 5);
INSERT INTO REFEICOES (TIPO_REFEICAO, DATA_REFEICAO, CAMPI, ID_ALUNO)VALUES('JANTAR', '2020-11-29', 'ANGICOS', 9);
INSERT INTO REFEICOES (TIPO_REFEICAO, DATA_REFEICAO, CAMPI, ID_ALUNO)VALUES('ALMOCO', '2020-11-29', 'MOSSORO', 4);
