INSERT INTO ALUNOS (MATRICULA, NOME_COMPLETO)VALUES(2019011235, 'ADRIANO PEREIRA DA COSTA');
INSERT INTO ALUNOS (MATRICULA, NOME_COMPLETO)VALUES(2018010134, 'ALICE IELLY SANTOS MARROCOS');
INSERT INTO ALUNOS (MATRICULA, NOME_COMPLETO)VALUES(2016020915, 'ADRIANO PEREIRA DA COSTA');
INSERT INTO ALUNOS (MATRICULA, NOME_COMPLETO)VALUES(2016020915, 'ANNA LUIZA DE ARAUJO FRUTUOSO');
INSERT INTO ALUNOS (MATRICULA, NOME_COMPLETO)VALUES(2019022827, 'ANNYSHERLE KARLA DE MACEDO VIANA CAVALCANTE');
INSERT INTO ALUNOS (MATRICULA, NOME_COMPLETO)VALUES(2016021169, 'EDIGELZA DE ABREU');
INSERT INTO ALUNOS (MATRICULA, NOME_COMPLETO)VALUES(2018010455, 'ERALDO PALHARES FERREIRA');
INSERT INTO ALUNOS (MATRICULA, NOME_COMPLETO)VALUES(2018022221, 'FABIO LUIZ MARIANO DA SILVA');
INSERT INTO ALUNOS (MATRICULA, NOME_COMPLETO)VALUES(2019010582, 'FRANCISCO JAEDSON CAMARA');
INSERT INTO ALUNOS (MATRICULA, NOME_COMPLETO)VALUES(2019010625, 'GABRIEL BARBOSA DOS SANTOS');

INSERT INTO REFEICOES (TIPO_REFEICAO, DATA_REFEICAO, CAMPI, STATUS_REFEICAO, ID_ALUNO)VALUES('ALMOCO', '2020-11-29', 'PAU_DOS_FERROS','CANCELADA', 2);
INSERT INTO REFEICOES (TIPO_REFEICAO, DATA_REFEICAO, CAMPI, STATUS_REFEICAO, ID_ALUNO)VALUES('ALMOCO', '2020-11-29', 'ANGICOS','ATIVA', 2);
INSERT INTO REFEICOES (TIPO_REFEICAO, DATA_REFEICAO, CAMPI, STATUS_REFEICAO, ID_ALUNO)VALUES('ALMOCO', '2020-11-29', 'MOSSORO','ATIVA', 2);
INSERT INTO REFEICOES (TIPO_REFEICAO, DATA_REFEICAO, CAMPI, STATUS_REFEICAO, ID_ALUNO)VALUES('ALMOCO', '2020-11-29', 'CARAUBAS','ATIVA', 2);
INSERT INTO REFEICOES (TIPO_REFEICAO, DATA_REFEICAO, CAMPI, STATUS_REFEICAO, ID_ALUNO)VALUES('ALMOCO', '2020-11-29', 'CARAUBAS','CANCELADA', 2);
INSERT INTO REFEICOES (TIPO_REFEICAO, DATA_REFEICAO, CAMPI, STATUS_REFEICAO, ID_ALUNO)VALUES('ALMOCO', '2020-11-29', 'ANGICOS','ATIVA', 2);

INSERT INTO USUARIOS (NOME_COMPLETO, USERNAME, PASSWORD) VALUES ('CESARIO','cesarionto','123456789');
INSERT INTO USUARIOS (NOME_COMPLETO, USERNAME, PASSWORD) VALUES ('xico','caralegal','528855');
INSERT INTO USUARIOS (NOME_COMPLETO, USERNAME, PASSWORD) VALUES ('igor','carinhalegal24','886666');